# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 285ed4d1150bab6913e3d95a4d36985e96add4d93a39565c837c5a14b1f6cde935cc0ef981236593f277cb58d416f661e0b97d6c6ace72e11fb88cc26a537a7e

test:
  secret_key_base: 50822448f135ad4c70fc881792403dd3a62dc9fd3a21d16e67f5d78fa8498b39200ab1265651bc7aacd14b945f98bfa79c196fac64c11449fef23a534cc62426

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
